# Data Cleaning and Preprocessing

## Importing Libraries

In [58]:
import pandas as pd

## Download dataset from huggingface

In [11]:
from huggingface_hub import login
from datasets import load_dataset
import pandas as pd

# Huggingface_hub Login
login()

"""# Loading the dataset into a pandas dataframe
df = pd.DataFrame(load_dataset("Tobi-Bueck/customer-support-tickets")['train'])

# Saving the dataset
df.to_csv("datasets/Customer_Support_Tickets.csv")"""

df = load_dataset("Tobi-Bueck/customer-support-tickets")['train'].to_pandas()

## Data Lookup

In [61]:
# First 5 rows
df.head()

,Unnamed: 0,subject,body,answer,type,queue,priority,language,version,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8
0,0,Wesentlicher Sicherheitsvorfall,"Sehr geehrtes Support-Team,\n\nich möchte eine...",Vielen Dank für die Meldung des kritischen Sic...,Incident,Technical Support,high,de,51.0,Security,Outage,Disruption,Data Breach,NaN,NaN,NaN,NaN
1,1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...","Thank you for reaching out, <name>. We are awa...",Incident,Technical Support,high,en,51.0,Account,Disruption,Outage,IT,Tech Support,NaN,NaN,NaN
2,2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Thank you for your inquiry. Our products suppo...,Request,Returns and Exchanges,medium,en,51.0,Product,Feature,Tech Support,NaN,NaN,NaN,NaN,NaN
3,3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",We appreciate you reaching out with your billi...,Request,Billing and Payments,low,en,51.0,Billing,Payment,Account,Documentation,Feedback,NaN,NaN,NaN
4,4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",Thank you for your inquiry. Our product suppor...,Problem,Sales and Pre-Sales,medium,en,51.0,Product,Feature,Feedback,Tech Support,NaN,NaN,NaN,NaN

In [62]:
# Last 5 rows
df.tail()

,Unnamed: 0,subject,body,answer,type,queue,priority,language,version,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8
61760,61760,Assistance Needed for IFTTT Docker Integration,I am facing integration problems with IFTTT Do...,I would be happy to assist with the IFTTT Dock...,Problem,Technical Support,low,en,NaN,Integration,Disruption,Performance,IT,Tech Support,NaN,NaN,NaN
61761,61761,Bitten um Unterstützung bei der Integration,"Sehr geehrte Kundenservice, ich möchte die Int...","Sehr geehrte [Name], vielen Dank für Ihren Kon...",Change,Technical Support,medium,de,NaN,Integration,Feature,Documentation,Tech Support,NaN,NaN,NaN,NaN
61762,61762,NaN,"Hello Customer Support, I am inquiring about t...",We will send you detailed information on plans...,Request,Billing and Payments,low,en,NaN,Billing,Payment,Feature,Feedback,Sales,Lead,NaN,NaN
61763,61763,Hilfe bei digitalen Strategie-Problemen,Die Qualität unserer digitalen Strategie-Bearb...,Um den digitalen Strategie-Impuls zu überprüfe...,Incident,Product Support,high,de,NaN,Feedback,Performance,IT,Tech Support,NaN,NaN,NaN,NaN
61764,61764,Optimierung Ihrer Datenanalyse-Plattform erlei...,"Sehr geehrte Customer Support-Team, ich schrei...","Sehr geehrter <name>, wir antworten Ihnen auf ...",Change,Sales and Pre-Sales,medium,de,NaN,Product,Feature,Performance,Guidance,Documentation,NaN,NaN,NaN

In [63]:
df.describe(include='all')

,Unnamed: 0,subject,body,answer,type,queue,priority,language,version,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8
count,61765.000000,56466,61763,48576,48587,61765,61765,61765,28587.000000,48587,48528,48356,43990,27636,13225,5968,2472
unique,NaN,46635,53364,40139,4,52,5,2,NaN,211,350,591,831,956,920,755,512
top,NaN,Systemausfall,A healthcare provider has encountered unauthor...,Please provide the integration steps and requi...,Incident,Technical Support,medium,de,NaN,Security,Performance,IT,Tech Support,Tech Support,Tech Support,Tech Support,Documentation
freq,NaN,3,2,2,19444,14186,23378,33504,NaN,9156,8698,9430,10004,6904,2606,512,166
mean,30882.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,278.382027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,17830.164025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165.962935,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,15441.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,30882.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,46323.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,61764.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61765 entries, 0 to 61764
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  61765 non-null  int64
 1   subject     56466 non-null  object
 2   body        61763 non-null  object
 3   answer      48576 non-null  object
 4   type        48587 non-null  object
 5   queue       61765 non-null  object
 6   priority    61765 non-null  object
 7   language    61765 non-null  object
 8   version     28587 non-null  float64
 9   tag_1       48587 non-null  object
 10  tag_2       48528 non-null  object
 11  tag_3       48356 non-null  object
 12  tag_4       43990 non-null  object
 13  tag_5       27636 non-null  object
 14  tag_6       13225 non-null  object
 15  tag_7       5968 non-null   object
 16  tag_8       2472 non-null   object
dtypes: float64(1), int64(1), object(15)
memory usage: 8.0+ MB

## Data Cleaning

### Removing excess feature columns

In [65]:
df.drop(columns={'Unnamed: 0'}, inplace=True)

### Missing values

In [66]:
# Calculate the percentage of missing values in each row
def per_missing_values(df):
    return df.isna().mean() * 100

per_missing_values(df)

subject      8.579292
body         0.003238
answer      21.353517
type        21.335708
queue        0.000000
priority     0.000000
language     0.000000
version     53.716506
tag_1       21.335708
tag_2       21.431231
tag_3       21.709706
tag_4       28.778434
tag_5       55.256213
tag_6       78.588197
tag_7       90.337570
tag_8       95.997733
dtype: float64